### PR TITLE
Develop #6

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ptatian I gave @maggiesu0725 some bad advice yesterday and asked her put the streetAlt file in the MAR report, which meant she couldn't commit on this branch. I asked her to move it into Vital in order to commit.

**Comment by ptatian** [comment]
Got it. Thank you.

**Comment by maggiesu0725** [comment]
@ptatian I did the spatial join in ArcGIS and there's an option to aggregate the counts in the output attributes so we don't have to do the aggregation separately. That said, I did try to use your code to do the aggregation in SAS, I  commented the code out in the birthgeocode program because there was an error.

**Comment by ptatian** [comment]
Thanks, @maggiesu0725. It is OK to merge the branch and then please do a final batch submit on L: after syncing the programs there with GitHub (double-click on L:\Libraries\Vital\Sync). Thank you!

**Pull request merged**
