### PR TITLE
compile population/ death data and summarize by geography and age group

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo could you also review this by tomorrow if possible?

**Comment by maggiesu0725** [comment]
@rpitingolo why did you add the 1000 multiplier?

**Comment by maggiesu0725** [comment]
the multiplier for mortality seems to be 100,000, just changed it @rpitingolo @lhendey

**Comment by lhendey** [comment]
@maggiesu0725 - all age group counts for population for females are still not in there. 

	agegroup_6= sum(pct13i13, pct13i14);
		agegroup_7= sum(pct13i15, pct13i16);
		agegroup_8 = sum(pct13i17, pct13i18, pct13i19);

**Comment by lhendey** [comment]
@maggiesu0725 https://factfinder.census.gov/bkmk/table/1.0/en/DEC/10_SF1/PCT13 see the table structure

**Comment by maggiesu0725** [comment]
I fixed it already, it should be updated, could you try fetch it on Github? @lhendey

**Comment by lhendey** [comment]
@maggiesu0725 thanks. some reason wasn't pulling.

**Comment by lhendey** [comment]
@maggiesu0725 okay to output

**Pull request merged**
