### PR TITLE
write program to summarize birth data

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by rpitingolo** [comment]
@maggiesu0725 good work on this. I will open a bugfix issue to deal with the numeric/character inconsistency issue. 

@ptatian In the %Super_transpose macro Yipeng tried to define var=Births_:, but it looks like that colon syntax doesn't work in the macro? Listing out all the variables we want to transpose isn't realistic. I suggested we could sue proc sql to create a varlist macro to define this parameter, but if you know of a better way that would be helpful. Thanks.

**Comment by ptatian** [comment]
@rpitingolo @maggiesu0725 Yes, you are right, you can't use the : wildcard with %Super_transpose(). Sorry for not noting that earlier. Other than doing a copy and past on the var list, the Proc Sql approach seems like a good workaround.

**Comment by rpitingolo** [comment]
@ptatian thanks. We'll go with the proc sql approach. @maggiesu0725

**Comment by rpitingolo** [comment]
@maggiesu0725 The code that you wrote but then commented out actually is correct. The reason (I think) it didn't work for you is because the syntax was a little off.

In SAS if you want to keep a row based on an observation you say `if var = "value";` You had written `keep if var = "value";` which I think is the correct syntax for Stata but won't work in SAS. I updated it and pushed a commit. As soon as I finish the bugfix issue then we can finalize this one. Thanks.

**Comment by rpitingolo** [comment]
@maggiesu0725 I think this is good to go now. Please run the program and check to make sure that all geographies are working correctly. If they are then you can merge, sync, and batch submit the program. Thanks.

**Pull request merged**
