### PR TITLE
adjust numerator for premature death for equity feature

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@lhendey @ptatian I'm not totally sure if we need the 1000 in the new formula of numerator

**Comment by lhendey** [comment]
@maggiesu0725 - can you actually reverse your changes? to be clear we want the rates to calculate as they were. 

we just want to output a new numerator so that the math works in the .csv you output. 
new numerator that is the denominator * the weighted rate. 

does that make sense?

**Comment by maggiesu0725** [comment]
@lhendey I didnt change the calculation of the premature death rate, I just changed the numerator to denominator * the weighted rate.  My rate calculation is directly from the death and population counts instead of numerator/denominator so it won't affect the rate. Are you saying I should keep the old numerator?

**Comment by lhendey** [comment]
@maggiesu0725 i see, sorry.

we're still not getting the right new numerator though. i think for simplicity's sake (and transparency), please reverse your changes.

to that data step create a new variable = to the denominator*equityvar (*1000).

**Comment by lhendey** [comment]
@maggiesu0725  i think you need to put the numerator after the equityvariable calculation.

**Comment by lhendey** [comment]
@maggiesu0725 okay to merge.

**Comment by lhendey** [comment]
@maggiesu0725 sorry - wrong one!

**Pull request merged**
